"""
Django settings for BackPage project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os  # new line
import dj_database_url  # new line
 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ql66se5%h8xfwq6^ulklzoln8)#966i-g5ng+u4j*5@!@w!ll%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'storages',
    'corsheaders',

    # my apps
    'authsystem',
    'artist',
    'video',
    'market',
    'ads',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BackPage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BackPage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL", default=f"sqlite:///{BASE_DIR}/db.sqlite3"),
        conn_max_age=600,
        ssl_require=False,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'authsystem.User'

# Email Backend (Console for development)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = config('APP_EMAIL')
EMAIL_HOST_PASSWORD = config('APP_PASS')


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=70),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=700),
}







import os

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='eu-north-1')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
AWS_S3_ADDRESSING_STYLE = "virtual"

# Verify S3 signatures (recommended)
AWS_S3_SIGNATURE_VERSION = 's3v4'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            # You can keep specific S3 options here if needed
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


CORS_ALLOWED_CREDENTIALS = True 

CORS_ALLOWED_ORIGINS = [ 
    'https://walleyed-manipulatively-katelynn.ngrok-free.dev',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://localhost:8888',
    'http://localhost:8000',
    'http://76.13.30.50',
    'http://76.13.30.50:8888',
    'https://admin.bpliberia.com',
    'http://admin.bpliberia.com',
    'http://10.10.13.57:8000',
    'https://backpage-liberia.netlify.app',
]
CORS_ALLOWED_ALL_ORIGINS = True

ALLOWED_HOSTS = ['localhost', '76.13.30.50', '127.0.0.1', '10.10.13.80', 'admin.bpliberia.com', '10.10.13.57:8000','backpage-liberia.netlify.app',]

CSRF_TRUSTED_ORIGINS = [
    'https://walleyed-manipulatively-katelynn.ngrok-free.dev',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://localhost:8000',
    'http://localhost:8888',
    'http://76.13.30.50',
    'https://76.13.30.50',
    'http://76.13.30.50:8888',
    'https://admin.bpliberia.com',
    'http://admin.bpliberia.com',
    'http://10.10.13.57:8000',
    'https://backpage-liberia.netlify.app',
]

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

COOKIES_FILE = config('COOKIES_FILE', default='/app/cookies.txt')



FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024 * 1024  # 1 TB

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "BackPage Admin",
    "SITE_HEADER": "BackPage",
    "SITE_URL": "/",
    "THEME": "dark",
    "COLORS": {
        "primary": {
            "50": "254 242 242",
            "100": "254 226 226",
            "200": "254 202 202",
            "300": "252 165 165",
            "400": "248 113 113",
            "500": "239 68 68",
            "600": "220 38 38",
            "700": "185 28 28",
            "800": "153 27 27",
            "900": "127 29 29",
            "950": "69 10 10",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Users & Auth"),
                "separator": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:authsystem_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Content Management"),
                "separator": True,
                "items": [
                    {
                        "title": _("Artists"),
                        "icon": "mic",
                        "link": reverse_lazy("admin:artist_artist_changelist"),
                    },
                    {
                        "title": _("Music"),
                        "icon": "music_note",
                        "link": reverse_lazy("admin:artist_music_changelist"),
                    },
                    {
                        "title": _("Music Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:artist_category_changelist"),
                    },
                    {
                        "title": _("Videos"),
                        "icon": "movie",
                        "link": reverse_lazy("admin:video_video_changelist"),
                    },
                    {
                        "title": _("Video Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:video_videocategory_changelist"),
                    },
                ],
            },
            {
                "title": _("Marketplace & Property"),
                "separator": True,
                "items": [
                    {
                        "title": _("Products"),
                        "icon": "shopping_bag",
                        "link": reverse_lazy("admin:market_product_changelist"),
                    },
                    {
                        "title": _("Product Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:market_productcategory_changelist"),
                    },
                    {
                        "title": _("Properties"),
                        "icon": "domain",
                        "link": reverse_lazy("admin:market_property_changelist"),
                    },
                ],
            },
            {
                "title": _("Ads"),
                "separator": True,
                "items": [
                    {
                        "title": _("Ads"),
                        "icon": "ads",
                        "link": reverse_lazy("admin:ads_ads_changelist"),
                    },
                    {
                        "title": _("Ads Pages"),
                        "icon": "category",
                        "link": reverse_lazy("admin:ads_adspage_changelist"),
                    },
                ],
            }
        ],
    },
}