# Generated by Django 6.0 on 2026-01-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
