# Generated by Django 6.0 on 2026-01-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('video', 'Video'), ('music', 'Music'), ('market', 'Market')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
