# Generated by Django 6.0 on 2026-01-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adspage_created_at_adspage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adspage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
