# Generated by Django 6.0 on 2026-01-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_adspage_created_at_alter_adspage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
