# Generated by Django 6.0 on 2026-01-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_created_at_product_status_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
