# Generated by Django 6.0 on 2026-01-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_propertycartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycartitem',
            name='quantity',
        ),
    ]
