# Generated by Django 6.0 on 2026-01-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_propertycartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='propertycartitem',
            options={'ordering': ['-created_at']},
        ),
    ]
