# Generated by Django 6.0 on 2026-01-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_type',
            field=models.CharField(blank=True, choices=[('trapco', 'Trapco'), ('hiphop', 'Hiphop')], null=True),
        ),
    ]
