# Generated by Django 6.0 on 2026-01-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_artist_options_alter_listen_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
        migrations.RenameField(
            model_name='listen',
            old_name='artist',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='total_downloads',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='total_listens',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='download',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='listen',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(choices=[('featured', 'Featured'), ('local', 'Local')], max_length=20),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_type',
            field=models.CharField(blank=True, choices=[('trapco', 'Trapco'), ('hiphop', 'Hiphop')], max_length=20, null=True),
        ),
    ]
