# Generated by Django 6.0 on 2026-01-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_alter_music_audio_alter_music_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
