# Generated by Django 6.0 on 2026-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_type',
            field=models.CharField(blank=True, choices=[('trapco', 'Trapco'), ('hiphop', 'Hiphop'), ('hipco', 'Hipco')], max_length=20, null=True),
        ),
    ]
