# Generated by Django 6.0 on 2026-01-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0011_musiccategory_alter_music_music_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicCategory',
            new_name='Category',
        ),
    ]
