# Generated by Django 6.0 on 2026-01-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_rename_musiccategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
