# Generated by Django 6.0 on 2026-01-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_music_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='user',
        ),
    ]
