# Generated by Django 6.0 on 2026-01-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
