# Generated by Django 6.0 on 2026-01-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_video_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoview',
            name='user',
        ),
    ]
